### ISSUE TITLE
Weights of trained models 

### ISSUE THREAD

**Issue by MahdiHajibabaei** [esw0116/DynaVSR#1]
Hi,

Interesting work! I was wondering whether you could share the weights of trained models for the people who are interested in just testing the model. Furthermore, is using the term sub-low-resolution more appropriate than super-low-resolution since the resolution of image you are referring to is lower than the original low-resolution image?

**Comment by esw0116** [comment]
Hello, sorry to keep you waiting for a long time.
I have just updated the repository and attached the pretrained model. You can download it via [Google drive](https://drive.google.com/drive/folders/10-gUO6zBeOpWEamrWKCtSkkUFukB9W5m).
Also, the PSNR of SLR image scale is reported higher because it is compared in small size. Making downcaled version of an image is much easier than upscaling.
